### ISSUE TITLE
bruh moment is not working

### ISSUE THREAD

**Issue by op0x59** [Arilis/Arilis-s-Mutlitool#2]
bruh bruh bruh bruh

**Comment by Arilis** [comment]
try turning it on and off bruh bruh bruh bruh

**Comment by SLauzzer** [comment]
epic bruh moment

**Comment by op0x59** [comment]
it says https://hackertarget.com/external-vulnerability-assessment/

**Comment by SLauzzer** [comment]
omg that error means you've been hacked11!!!11
